#!/bin/bash

# Touchpad properties
xinput set-prop "DLLC6AD:00 06CB:75BF Touchpad" "Synaptics Scrolling Distance" -30, 30

export HPMONITOR=0x00400004
export FGCOLOR="$(cat $HOME/.cache/wal/colors | cut -d $'\n' -f 3)"

xrandr --output HDMI1 --mode 1920x1080
xrandr --output HDMI1 --right-of eDP1

sxhkd -m -1 &
polybar --reload bspwm &
polybar --reload bspwm2 &
compton &

bspc monitor -d I II III 
bspc monitor $HPMONITOR -d IV V VI


bspc config border_width        2 #2
bspc config window_gap          0 #10

bspc config focused_border_color	$FGCOLOR	
bspc config automatic_scheme	longest_side

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a *:* state=pseudo_tiled 
bspc rule -a Alacritty:weather state=floating
bspc rule -a "Firefox":"*" monitor=$HPMONITOR

wal --theme base16-grayscale
feh --bg-fill --randomize $(find $HOME/Pictures/**/*)

cd $HOME/start-page/
bundle exec jekyll serve . &
